imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  snc_redis.session.handler
        cookie_lifetime: 1800
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

# app/config/config.yml
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User

# Web Socket Configuration
gos_web_socket:
  server:
    port: "%websocket_port%"
    host: "%websocket_host%"
    router:
        resources:
            - '@AppBundle/Resources/config/pubsub/routing.yml'
  client:
    firewall: main
    session_handler: snc_redis.session.handler
#    storage:
#      driver: gos_web_socket.client_storage.driver.predis

# Redis Configuration
snc_redis:
  clients:
    default:
      type: predis
      alias: default
      dsn: '%redis_dsn%'
    session:
      type: predis
      alias: session
      dsn: '%redis_dsn%'
#    ws_client:
#      type: predis
#      alias: client_storage.driver #snc_redis.client_storage.driver
#      dsn: redis://localhost/2
#      logging: '%kernel.debug%'
#      options:
#          profile: 2.2
#          connection_timeout: 10
#          read_write_timeout: 30
  session:
    client: session
    locking: false