services:
    acme_hello.topic_sample_service:
        class: AppBundle\Topic\AcmeTopic
        arguments:
            - '@gos_web_socket.websocket.client_manipulator'
            - '@snc_redis.default'
        tags:
            - { name: gos_web_socket.topic }

    acme_hello.rpc_sample_service:
        class: AppBundle\Rpc\AcmeRpc
        tags:
            - { name: gos_web_socket.rpc }

#    gos_web_socket.client_storage.driver.predis:
#        class: Gos\Bundle\WebSocketBundle\Client\Driver\PredisDriver
#        arguments:
#            - '@snc_redis.client_storage.driver'
#            - '%web_socket_server.client_storage.prefix%' #(optionally)if you use prefix