acme_topic:
    channel: acme/{chname}
    handler:
        callback: 'acme.topic' #related to the getName() of your topic
    requirements:
        chname:
          pattern: "\d+"

acme_rpc:
    channel: sample/{method}
    handler:
        callback: 'acme.rpc' #related to the getName() or your RPC service
    requirements:
        method:
            pattern: "[a-z_]+"
