acme_topic:
    channel: acme/{room}
    handler:
        callback: 'acme.topic' #related to the getName() of your topic
    requirements:
        room:
            path: '\d+'

acme_rpc:
    channel: sample/{method}
    handler:
        callback: 'acme.rpc' #related to the getName() or your RPC service
    requirements:
        method:
            path: '[a-z_]+'
